project:
  type: website
  resources:
    - fonts
  preview:
    port: 4321

execute:
  freeze: auto
  
website:
  title: "Advent of Code 2023"
  #site-url: https://github.com
  description: My solutions to Advent of Code
  repo-url: https://francisbarton.github.io/adventofcode_2023/
  navbar:
    right:
      - icon: github
        href: https://github.com/francisbarton/adventofcode_2023
  open-graph: true

format:
  html:
    theme: 
      light: [cosmo, custom-light.scss]
      dark: custom-dark.scss
    css: styles.css
    code-block-border-left: true
    smooth-scroll: true
    link-external-newwindow: true

editor: source
